export const CONNECT_SOCKET = "CONNECT_SOCKET";

// ticker
export const INITIALIZE_TICKER_CHANNEL = "INITIALIZE_TICKER_CHANNEL";
export const SAVE_TICKER = "SAVE_TICKER";
export const SET_TICKER_PAIR = "SET_TICKER_PAIR";
export const SAVE_PAIR_DATA = "SAVE_PAIR_DATA";
export const RESET_TICKER_PAIR = "RESET_TICKER_PAIR";
export const START_TICKER_PAIR_SOCKET = "START_TICKER_PAIR_SOCKET";

// redux websocket types
export const MESSAGE = "REDUX_WEBSOCKET::MESSAGE";
export const OPEN = "REDUX_WEBSOCKET::OPEN";
export const ERROR = "REDUX_WEBSOCKET::ERROR";
export const BROKEN = "REDUX_WEBSOCKET::BROKEN";
export const BEGIN_RECONNECT = "REDUX_WEBSOCKET::BEGIN_RECONNECT";
export const CLOSED = "REDUX_WEBSOCKET::CLOSED";
// toast
export const SHOW_TOAST = "SHOW_TOAST";
export const SHOW_ERROR_TOAST = "SHOW_ERROR_TOAST";
export const SHOW_SUCCESS_TOAST = "SHOW_SUCCESS_TOAST";
export const SHOW_INFO_TOAST = "SHOW_INFO_TOAST";
export const HIDE_TOAST = "HIDE_TOAST";

// book
export const INITIALIZE_BOOK_CHANNEL = "INITIALIZE_BOOK_CHANNEL";
export const RESET_BOOK_CHANNEL = "RESET_BOOK_CHANNEL";
export const SAVE_BOOK = "SAVE_BOOK";
// trades
export const INITIALIZE_TRADES_CHANNEL = "INITIALIZE_TRADES_CHANNEL";
export const SAVE_TRADES = "SAVE_TRADES";
export const RESET_TRADES_CHANNEL = "RESET_TRADES_CHANNEL";
