export const INITIALIZE_TICKER_CHANNEL = "INITIALIZE_TICKER_CHANNEL";

export const SAVE_TICKER = "SAVE_TICKER";

export const SET_TICKER_PAIR = "SET_TICKER_PAIR";
export const SAVE_PAIR_DATA = "SET_TICKER_PAIR";
export const RESET_TICKER_PAIR = "RESET_TICKER_PAIR";
export const START_TICKER_PAIR_SOCKET = "START_TICKER_PAIR_SOCKET";
