export const CONNECT_SOCKET = "CONNECT_SOCKET";
export const INITIALIZE_TICKER_CHANNEL = "INITIALIZE_TICKER_CHANNEL";

export const SAVE_TICKER = "SAVE_TICKER";

export const SET_TICKER_PAIR = "SET_TICKER_PAIR";
export const SAVE_PAIR_DATA = "SAVE_PAIR_DATA";
export const RESET_TICKER_PAIR = "RESET_TICKER_PAIR";
export const START_TICKER_PAIR_SOCKET = "START_TICKER_PAIR_SOCKET";

// redux websocket types
export const MESSAGE = "REDUX_WEBSOCKET::MESSAGE";
export const OPEN = "REDUX_WEBSOCKET::OPEN";

// toast
export const SHOW_TOAST = "SHOW_TOAST";
export const SHOW_ERROR_TOAST = "SHOW_ERROR_TOAST";
export const SHOW_SUCCESS_TOAST = "SHOW_SUCCESS_TOAST";
export const HIDE_TOAST = "HIDE_TOAST";
